server:
  port: 8081

spring:
  application:
    name: language-recall-service
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: chat
          #          uri: lb://language-recall-service
          uri: forward:/api/chat
          predicates:
            - Path=/ollama/api/chat/**
        - id: ollama-proxy
          uri: http://localhost:11434
          predicates:
            - Path=/ollama/**
          filters:
            - StripPrefix=1
            - DedupeResponseHeader=Access-Control-Allow-Origin Vary
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3-vl:4b
        options:
          temperature: 0.7
logging:
  level:
    #    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.cors: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health
